spring:
    application:
        name: Service8001
    rabbitmq:
        host: localhost
        port: 5672
        username: ewf
        password: ewf
        virtual-host: /ewf
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
