server:
    port: 3000
spring:
    application:
        name: SecurityOAuth-Resource
#    cloud:
#        nacos:
#            discovery:
#                server-addr: localhost:8848
#logging:
#    level:
#        org.springframework.web: debug
