server:
    port: 2000
spring:
    application:
        name: Security-OAuth-Server2000
    datasource:
        url: jdbc:mysql://hasdsd.cn:3307/cloudtest
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
