server:
    port: 81
spring:
    application:
        name: E-WoodFish-Client
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://hasdsd.cn:3307/ewoodfish?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
logging:
    level:
        org.springframework.security: debug
